import './globals.css';
import type { Metadata } from 'next';

import { Inter, Monoton, Roboto, Poppins } from 'next/font/google';
import TanstackQueryProvider from '@/provider/TanstackQueryProvider';
import SessionWrapper from "./providers/SessionWrapper";
import FcmClientProvider from "./providers/FcmClientProvider";
import { getServerSession } from 'next-auth';
import { options } from './api/auth/[...nextauth]/options';


const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const monoton = Monoton({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-monoton',
});
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto',
});
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: 'VYBZ',
  description: 'Generated by create turbo',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);
  // const { data: session } = useSession();
  return (
    <html
      lang="en"
      className={`${inter.variable} ${monoton.variable} ${roboto.variable} ${poppins.variable}`}
    >
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#000000" />
        <link rel="icon" href="https://vybz.s3.ap-northeast-2.amazonaws.com/vybz_logo.png" />
      </head>
      <body className="font-inter">
        <TanstackQueryProvider>
          <SessionWrapper session={session}>
            <FcmClientProvider />
            {children}
          </SessionWrapper>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
