import './globals.css';
import type { Metadata } from 'next';
import { Inter, Monoton, Roboto, Poppins } from 'next/font/google';
import TanstackQueryProvider from '@/provider/TanstackQueryProvider';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const monoton = Monoton({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-monoton',
});
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto',
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: 'VYBZ',
  description: 'Generated by create turbo',
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${monoton.variable} ${roboto.variable} ${poppins.variable}`}
    >
      <body className="font-inter">
        <TanstackQueryProvider>{children}</TanstackQueryProvider>
      </body>
    </html>
  );
}
